yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница.
    path('', views.index, name='index'),
    # Страницы с группами постов.
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя.
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи.
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи.
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи.
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария.
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Список постов только авторов на которых мы подписаны.
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на автора.
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка от автора.
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView as PCDV
from django.contrib.auth.views import PasswordChangeView as PCV
from django.contrib.auth.views import PasswordResetCompleteView as PRCmV
from django.contrib.auth.views import PasswordResetConfirmView as PRCnV
from django.contrib.auth.views import PasswordResetDoneView as PRDV
from django.contrib.auth.views import PasswordResetView as PRV
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        PCV.as_view(template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PCDV.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PRV.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PRDV.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PRCnV.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PRCmV.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
</article>
{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы
  </a>
{% endif %}

yatube/templates/includes/footer.html
{% comment "Demo note for learn only" %}
  тег span используется для добавления нужных стилей отдельным участкам текста
{% endcomment %}
<p>
  © {{ year }} Copyright <span style="color:red">Ya</span>tube
</p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %} active {% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %} active {% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %} active {% endif %}"
              href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %} active {% endif %}"
              href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %} active {% endif %}"
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %} active {% endif %}"
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}

yatube/templates/includes/switcher.html
<!-- templates/posts/includes/switcher.html -->

{% if user.is_authenticated %}
  {% with request.resolver_match.view_name as view_name %}
    <div class="row my-3">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a 
            class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}"
            href="{% url 'posts:index' %}"
          >
            Все авторы
          </a>
        </li>
        <li class="nav-item">
          <a 
            class="nav-link {% if view_name == 'posts:follow_index' %}active{% endif %}"
            href="{% url 'posts:follow_index' %}"
          >
            Избранные авторы
          </a>
        </li>
      </ul>
    </div>
  {% endwith %}
{% endif %}