yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница.
    path('', views.index, name='index'),
    # Страницы с группами постов.
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя.
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи.
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи.
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи.
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария.
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Список постов только авторов на которых мы подписаны.
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на автора.
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка от автора.
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import PubDateModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
# Limit for __str__ method Post
LIMIT_STR: int = 15


class Post(PubDateModel):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста',
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа поста',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:LIMIT_STR]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название',
        help_text='Название группы',
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        verbose_name='url',
        help_text='Адрес страницы',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(PubDateModel):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Автор комментария',
    )
    text = models.TextField(
        max_length=200,
        verbose_name='Комментарий',
        help_text='Комментарий к посту',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        null=False,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик',
    )
    author = models.ForeignKey(
        User,
        null=False,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор на которого подписан',
        help_text='Автор на кого подписываемся',
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_texts = {
            'text': 'Текст нового поста.',
            'group': 'Группа поста.',
            'image': 'Картинка к посту.'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий'}
        help_texts = {'text': 'Комментарий'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .addons import paginator
from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User

# Numbers of title length
TITLE_LENGTH: int = 30


def index(request):
    template = 'posts/index.html'
    title = "Последние обновления на сайте"
    posts = Post.objects.select_related('author', 'group').all()
    page_obj = paginator(request, posts)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = group.posts.select_related('author', 'group').all()
    page_obj = paginator(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    title = f'Профайл пользователя { author.get_full_name() }'
    posts = (
        Post
        .objects
        .select_related('author', 'group')
        .filter(author=author)
    )
    count = posts.count()
    page_obj = paginator(request, posts)
    if request.user.is_authenticated:
        following = (
            Follow
            .objects
            .filter(user=request.user, author=author)
            .exists()
        )
    else:
        following = False
    if request.user == author:
        user_not_author = True
    else:
        user_not_author = False
    context = {
        'author': author,
        'title': title,
        'page_obj': page_obj,
        'count': count,
        'following': following,
        'user_not_author': user_not_author,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = Post.objects.get(pk=post_id)
    title = post.text[:TITLE_LENGTH]
    count = Post.objects.filter(author=post.author).count()
    form = CommentForm()
    comments = Comment.objects.select_related('author').filter(post=post.id)
    context = {
        'post_id': post_id,
        'post': post,
        'count': count,
        'title': title,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        form.instance.author = request.user
        form.instance.post = post
        form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    title = 'Добавить запись'
    form = PostForm(
        request.POST or None,
        request.FILES or None,
    )
    if form.is_valid():
        text = form.cleaned_data['text']
        group = form.cleaned_data['group']
        image = form.cleaned_data['image']
        author = request.user
        Post.objects.create(text=text, author=author, group=group, image=image)
        return redirect('posts:profile', username=request.user)
    context = {
        'form': form,
        'title': title,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    template = 'posts/create_post.html'
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    title = 'Редактировать запись'
    is_edit = True
    form = PostForm(
        instance=post,
        data=request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'title': title,
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    title = "Последние обновления авторов"
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, posts)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    user = request.user
    author = get_object_or_404(User, username=username)
    follower_count = Follow.objects.filter(user=user, author=author).count()
    if user != author and follower_count == 0:
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    # Отписаться от автора
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{# templates/posts/create_post.html #}

{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {{ title }}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %} >
              {% csrf_token %}
              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <p>
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </p>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{# templates/posts/follow.html #}

{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  {% load cache %}
  {% cache 20 follow_page %}
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{# templates/posts/group_list.html #}

{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group }}
{% endblock %}
{% block content %}
  <h1>{{ group }}</h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{# templates/posts/index.html #}

{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  {% load cache %}
  {% cache 20 index_page %}
    {% for post in page_obj %}
      {% include 'includes/article.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/paginator.html
{# templates/posts/paginator.html #}

{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">
              {{ i }}
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">
              {{ i }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/post_detail.html
{# templates/posts/post_detail.html #}

{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
              <p>
              {{ comment.text }}
              </p>
            </div>
          </div>
      {% endfor %} 
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{# templates/posts/profile.html #}

{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ count }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      {% if not user_not_author %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}